kind: Pod 
apiVersion: v1
metadata:
  name: nodelabel
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true;do echo Hello-Piyush; sleep 5;done"]
  nodeSelector:               # specifies which node to run the pod
    mynode: piyush              # can give any label
