kind: Pod
apiVersion: v1
metadata:
  name: testpod2
  annotations:              #description describe the object usage
   description: our first testpod
spec: 
 containers:
   - name: c00
     image: ubuntu
     command: ["/bin/bash","-c","while true; do echo Hello-Piyush; sleep 5; done"]
