apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcontroller
spec:
  replicas: 2
  selector:
    myname: piyush
  template:
    metadata:
      labels:
        myname: piyush
    spec:
      containers:
        - name: c00
          image: busybox
          command: ["/bin/sh","-c","while true; do echo Hello-Piyush; sleep 5; done"]

